// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIAutoUITestingExercisWindow UIAutoUITestingExercisWindow
        {
            get
            {
                if ((this.mUIAutoUITestingExercisWindow == null))
                {
                    this.mUIAutoUITestingExercisWindow = new UIAutoUITestingExercisWindow();
                }
                return this.mUIAutoUITestingExercisWindow;
            }
        }
        
        public UIAutoUITestingExercisWindow1 UIAutoUITestingExercisWindow1
        {
            get
            {
                if ((this.mUIAutoUITestingExercisWindow1 == null))
                {
                    this.mUIAutoUITestingExercisWindow1 = new UIAutoUITestingExercisWindow1();
                }
                return this.mUIAutoUITestingExercisWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIAutoUITestingExercisWindow mUIAutoUITestingExercisWindow;
        
        private UIAutoUITestingExercisWindow1 mUIAutoUITestingExercisWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAutoUITestingExercisWindow : WpfWindow
    {
        
        public UIAutoUITestingExercisWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Auto UI Testing Exercise - Richard Sims - 9633324";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Auto UI Testing Exercise - Richard Sims - 9633324");
            #endregion
        }
        
        #region Properties
        public WpfButton UIStartButton
        {
            get
            {
                if ((this.mUIStartButton == null))
                {
                    this.mUIStartButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStartButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "button1";
                    this.mUIStartButton.WindowTitles.Add("Auto UI Testing Exercise - Richard Sims - 9633324");
                    #endregion
                }
                return this.mUIStartButton;
            }
        }
        
        public WpfCheckBox UICheckboxCheckBox
        {
            get
            {
                if ((this.mUICheckboxCheckBox == null))
                {
                    this.mUICheckboxCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUICheckboxCheckBox.SearchProperties[WpfCheckBox.PropertyNames.AutomationId] = "checkBox1";
                    this.mUICheckboxCheckBox.WindowTitles.Add("Auto UI Testing Exercise - Richard Sims - 9633324");
                    #endregion
                }
                return this.mUICheckboxCheckBox;
            }
        }
        
        public WpfButton UIStartButton1
        {
            get
            {
                if ((this.mUIStartButton1 == null))
                {
                    this.mUIStartButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIStartButton1.SearchProperties[WpfButton.PropertyNames.AutomationId] = "buttonA";
                    this.mUIStartButton1.WindowTitles.Add("Auto UI Testing Exercise - Richard Sims - 9633324");
                    #endregion
                }
                return this.mUIStartButton1;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIStartButton;
        
        private WpfCheckBox mUICheckboxCheckBox;
        
        private WpfButton mUIStartButton1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAutoUITestingExercisWindow1 : WinWindow
    {
        
        public UIAutoUITestingExercisWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Auto UI Testing Exercise - Richard Sims - 9633324";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Auto UI Testing Exercise - Richard Sims - 9633324");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIAutoUITestingExercisTitleBar
        {
            get
            {
                if ((this.mUIAutoUITestingExercisTitleBar == null))
                {
                    this.mUIAutoUITestingExercisTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIAutoUITestingExercisTitleBar.WindowTitles.Add("Auto UI Testing Exercise - Richard Sims - 9633324");
                    #endregion
                }
                return this.mUIAutoUITestingExercisTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIAutoUITestingExercisTitleBar;
        #endregion
    }
}
